model:
    type: resnet50
    output_dim: 2048
    
    kwargs:
        pretrain_path: /mnt/lustre/zhangyuanhan/weights/swav/swav_800ep

data:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    input_size: 224
