model:
    type: modified_res50
    output_dim: 1024

    kwargs:
        pretrain_path: /mnt/lustre/zhangyuanhan/CLIP-RN50.pth
        enable_attnpool: True
        enable_fc: False
        bn:
            use_sync_bn: False
            kwargs: {}
data:
    mean: [0.48145466, 0.4578275, 0.40821073]
    std: [0.26862954, 0.26130258, 0.27577711]
    input_size: 224
