model:
    type: timm_vit
    output_dim: 768

    kwargs:
        pretrain_path: /mnt/lustre/yhzhang/weights/Vision_Transformer/ViT-B_16.npz
data:
    mean: [0.48145466, 0.4578275, 0.40821073]
    std: [0.26862954, 0.26130258, 0.27577711]
    input_size: 224